apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: envoy-routing
build:
  artifacts:
  - image: backend-img
    context: backend
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s1/backend-svc.yaml
    - k8s1/backend-deployment.yaml
    - k8s1/ingress.yaml
    - k8s1/lb.yaml